### ISSUE TITLE
ES fails for queries which yield longitude < -180

### ISSUE THREAD

**Issue by nilsnolde** [pelias/pelias#750]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
looked in the ES server logs, as they were growing up to 20 GB per day..

---
#### Here's what I got :scream_cat:
Tons of exceptions saying `QueryParsingException[illegal longitude value [-207.21826713725756] for [geo_bbox]]` or other values smaller than -180.

Complete log entry:

```
[2018-10-13 10:37:47,518][DEBUG][action.search            ] [ors-pelias-n2] All shards failed for phase: [dfs]
RemoteTransportException[[ors-pelias-n3][192.168.2.73:9300][indices:data/read/search[phase/dfs]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"match":{"name.default":{"analyzer":"peliasQueryFullToken","boost":1,"query":"halifa"}}}],"should":[{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},{"function_score":{"query":{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},"max_boost":20,"functions":[{"field_value_factor":{"modifier":"log1p","field":"popularity","missing":1},"weight":1}],"score_mode":"first","boost_mode":"replace"}},{"function_score":{"query":{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},"max_boost":20,"functions":[{"field_value_factor":{"modifier":"log1p","field":"population","missing":1},"weight":2}],"score_mode":"first","boost_mode":"replace"}}],"filter":[{"geo_bounding_box":{"type":"indexed","center_point":{"top":75.04321994867347,"right":-36.18311088724795,"bottom":-14.630751639307494,"left":-207.21826713725756}}},{"terms":{"layer":["venue","continent","empire","country","dependency","macroregion","region","locality","localadmin","macrocounty","county","macrohood","borough","neighbourhood","microhood","disputed","postalcode","ocean","marinearea"]}}]}},"size":20,"track_scores":true,"sort":["_score"]}]]; nested: QueryParsingException[illegal longitude value [-207.21826713725756] for [geo_bbox]];
Caused by: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"match":{"name.default":{"analyzer":"peliasQueryFullToken","boost":1,"query":"halifa"}}}],"should":[{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},{"function_score":{"query":{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},"max_boost":20,"functions":[{"field_value_factor":{"modifier":"log1p","field":"popularity","missing":1},"weight":1}],"score_mode":"first","boost_mode":"replace"}},{"function_score":{"query":{"match":{"phrase.default":{"analyzer":"peliasPhrase","type":"phrase","boost":1,"slop":2,"query":"halifa"}}},"max_boost":20,"functions":[{"field_value_factor":{"modifier":"log1p","field":"population","missing":1},"weight":2}],"score_mode":"first","boost_mode":"replace"}}],"filter":[{"geo_bounding_box":{"type":"indexed","center_point":{"top":75.04321994867347,"right":-36.18311088724795,"bottom":-14.630751639307494,"left":-207.21826713725756}}},{"terms":{"layer":["venue","continent","empire","country","dependency","macroregion","region","locality","localadmin","macrocounty","county","macrohood","borough","neighbourhood","microhood","disputed","postalcode","ocean","marinearea"]}}]}},"size":20,"track_scores":true,"sort":["_score"]}]]; nested: QueryParsingException[illegal longitude value [-207.21826713725756] for [geo_bbox]];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:264)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:360)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:357)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: [pelias_all_alt] QueryParsingException[illegal longitude value [-207.21826713725756] for [geo_bbox]]
	at org.elasticsearch.index.query.GeoBoundingBoxQueryParser.parse(GeoBoundingBoxQueryParser.java:168)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:263)
	at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:129)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:324)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:224)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:219)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
	... 12 more
```

---
#### Here's what I was expecting :sparkles:
Maybe: ES/pelias to wrap longitude < -180 (maybe similar problem for > 180?) to `-180 < long >180`

**Comment by missinglink** [comment]
Elasticsearch 2.x doesn't seem to handle 'wrapped coordinates', so we have a helper here https://github.com/pelias/api/blob/master/test/unit/sanitizer/wrap.js

It's implemented here https://github.com/pelias/api/blob/master/sanitizer/_geo_common.js, so there must be some parameter which isn't being handled by this.

**Comment by missinglink** [comment]
Agh it's the `geo_bounding_box` filter which is causing it, bounding boxes are a little harder to wrap than points, I'd need to find an algorithm to do this.

**Comment by missinglink** [comment]
```
{
  "top":75.04321994867347,
  "right":-36.18311088724795,
  "bottom":-14.630751639307494,
  "left":-207.21826713725756
}
```

**Comment by missinglink** [comment]
The bounds above cannot be represented by a single box within `90/-90 180/-180`, it would have to be cut into two bounding boxes in order to cover the intended area without clipping.

**Comment by missinglink** [comment]
I think this is why we decided to use the convention `boundary.rect.min_lat, boundary.rect.min_lon, boundary.rect.max_lat=, oundary.rect.max_lon=`

@nilsnolde I think if you check your input you'll find that in these cases your `maxLon` is lesser than your `minLon`.

Still, it would be nice if pelias could handle this case, cut the wrapped rectangle in to two or more bounding boxes and then use them for the query.

I would suggest holding off on any feature work here until we finish the migration to elasticsearch 5 which is underway.

Elasticsearch prior to 2 used to wrap correctly, then wrapping was broken in 2, so maybe it's fixed again in 5?

**Comment by missinglink** [comment]
ref: https://github.com/pelias/api/issues/570

**Comment by nilsnolde** [comment]
ok, thanks for the heads-up @missinglink!

We installed netdata for now to warn us for volume issues due to ES log size. And then looking forward to ES5:) Maybe the automagic wrapper is back there!

**Comment by orangejulius** [comment]
I took a look at this yesterday morning while enjoying some nice tea, and at least improved the error messages returned in this and some other cases, by catching this situation in the API before even querying Elasticsearch. Take a look at https://github.com/pelias/api/pull/1207 which should prevent log bloat immediately.

We can decide later if we want to get fancy with handling wrapping for bounding boxes. I think it's considerably more complicated than for a single point.

**Comment by nilsnolde** [comment]
Oh that's great, thanks! ES error logs have a huge traceback..
