### ISSUE TITLE
Please update Pelias software requirements doc with the supported Node.js versions

### ISSUE THREAD

**Issue by sayanb1983** [pelias/pelias#765]
In the Pelias [software requirements documentation](https://github.com/pelias/documentation/blob/master/requirements.md), Node 8 and 10 are mentioned, but there is no mention of the specific minor version numbers.

For now, I think Pelias supports upto v8.13.0 and v10.13.0.

Usage of Node versions greater than this while creating the pelias index will result in "HPE_HEADER_OVERFLOW" error from node, with  the following stacktrace,

```
PUT http://localhost:9200/pelias => Parse Error
      at Log.error (/mnt/imports/pelias/schema/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/mnt/imports/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:266:18)
      at HttpConnector.<anonymous> (/mnt/imports/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.j
s:163:7)
      at ClientRequest.wrapper (/mnt/imports/pelias/schema/node_modules/lodash/lodash.js:4935:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketOnData (_http_client.js:448:9)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
```
This is due to the fact that Elasticsearch sends a lot of deprecation warnings as headers, which leads to large header size, and Node.js have added a security feature limiting the header size.

For more reference, please check these following commits in [pelias/schema](https://github.com/pelias/schema/),

- https://github.com/pelias/schema/commit/a285caef7d84ec3c23a126646a5be9041256aef3

- https://github.com/pelias/schema/commit/7b028d4e1d5c8b763206664fbd2e8939e92aae4a

**Comment by missinglink** [comment]
@orangejulius I remember us talking about this `HPE_HEADER_OVERFLOW` issue but forget the resolution, do we just want to make it clear in the docs which ones are unaffected?

@sayanb1983 what I do remember about it is that it's caused by the combination of nodejs version and elasticsearch version. I'm assuming you're running elasticsearch `5.6`?

Related: https://github.com/elastic/elasticsearch/issues/36243

**Comment by missinglink** [comment]
Possible workaround: https://github.com/nodejs/node/pull/24811

**Comment by orangejulius** [comment]
Yes, that CLI parameter to adjust the allowed header size allows us to use the latest Node.js version. A PR to pelias/schema is coming.
