### ISSUE TITLE
Error: "sqlite" is not allowed

### ISSUE THREAD

**Issue by sophia-xll** [pelias/pelias#796]
Hello,everyone.
I have download `whosonfirst-data-latest.db` on disk,  and just wants to use API geocoding server.Command as follow:
sudo pelias elastic start
sudo pelias elastic wait
sudo pelias elastic create
sudo pelias import wof

pelias.json like this:

    "whosonfirst": {
      "datapath": "/data/whosonfirst",
      "sqlite": true
    },

errors occure:

/code/pelias/whosonfirst/node_modules/pelias-config/index.js:37
    throw new Error(validationResult.error.details[0].message);
    ^

Error: "sqlite" is not allowed
    at getValidatedSchema (/code/pelias/whosonfirst/node_modules/pelias-config/index.js:37:11)
    at Object.generate (/code/pelias/whosonfirst/node_modules/pelias-config/index.js:27:12)
    at Object.<anonymous> (/code/pelias/whosonfirst/import.js:1:109)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

Why this happen? How to solve this problem? Thanks for any help.

**Comment by missinglink** [comment]
Please update your docker images with `pelias compose pull` and try again
