### ISSUE TITLE
Suggest Nearby throws a 503

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#84]
Odd behavior around ```/suggest/nearby``` in prod (pelias.mapzen.com) service. 

The following URLs dont work:
https://pelias.mapzen.com/suggest/nearby?input=east&lat=41.9184&lon=-87.6493&size=10
https://pelias.mapzen.com/suggest/nearby?input=east&lat=41.9184&lon=-87.6493&size=10&zoom=3

But this works:
https://pelias.mapzen.com/suggest/nearby?input=east&lat=41.9184&lon=-87.6493&size=10&zoom=4

which leads me to believe that there is something weird going on with the suggester trying to use precision level 1. If you do not pass in the optional ```zoom``` parameter, by default the suggester query constructor assumes its zoom 1-3 and falls back to precision 1 (which is the lowest precision level). Here's the relevant line of code 11:35
https://github.com/pelias/api/blob/master/query/suggest.js#L27

However, we need to do some more investigation around the production instance and see if its an Ops related bug. The reason I say that is because it seems to work locally and in dev instances. @heffergm may be able to provide more insight if its an ops issue? 

@sevko could you dig a little deeper through the code and report if its a bug in our queries/sanitizers etc?

Thank you Blane Bell for bringing this to our attention. We are on it :)

**Comment by heffergm** [comment]
Query throws the following stack trace:

```
2015-04-30_15:55:47.02668 _writableState.buffer is deprecated. Use _writableState.getBuffer() instead.
2015-04-30_15:55:47.02779 /srv/www/api/releases/20150428191922/node_modules/geojson-extent/node_modules/geojson-coords/node_modules/geojson-flatten/index.js:11
2015-04-30_15:55:47.02784             return flatten(gj.geometry).map(function(geom) {
2015-04-30_15:55:47.02789                                         ^
2015-04-30_15:55:47.02793 TypeError: undefined is not a function
2015-04-30_15:55:47.02797     at flatten (/srv/www/api/releases/20150428191922/node_modules/geojson-extent/node_modules/geojson-coords/node_modules/geojson-flatten/index.js:11:41)
2015-04-30_15:55:47.02802     at /srv/www/api/releases/20150428191922/node_modules/geojson-extent/node_modules/geojson-coords/node_modules/geojson-flatten/index.js:7:35
2015-04-30_15:55:47.02806     at Array.reduce (native)
2015-04-30_15:55:47.02810     at flatten (/srv/www/api/releases/20150428191922/node_modules/geojson-extent/node_modules/geojson-coords/node_modules/geojson-flatten/index.js:6:39)
2015-04-30_15:55:47.02814     at module.exports (/srv/www/api/releases/20150428191922/node_modules/geojson-extent/node_modules/geojson-coords/index.js:7:22)
2015-04-30_15:55:47.02818     at getExtent (/srv/www/api/releases/20150428191922/node_modules/geojson-extent/index.js:25:18)
2015-04-30_15:55:47.02821     at module.exports (/srv/www/api/releases/20150428191922/node_modules/geojson-extent/index.js:6:12)
2015-04-30_15:55:47.02824     at search (/srv/www/api/releases/20150428191922/helper/geojsonify.js:65:18)
2015-04-30_15:55:47.02827     at reply (/srv/www/api/releases/20150428191922/controller/suggest.js:30:21)
2015-04-30_15:55:47.02829     at /srv/www/api/releases/20150428191922/controller/suggest.js:69:16
```

**Comment by missinglink** [comment]
upstream PR opened: https://github.com/caseypt/GeoJSON.js/pull/12

**Comment by missinglink** [comment]
failing test case:

```javascript
// ref: https://github.com/pelias/pelias/issues/84
module.exports.tests.earth = function(test, common) {

  var earth = [{
    '_index': 'pelias',
    '_type': 'geoname',
    '_id': '6295630',
    'name': {
      'default': 'Earth'
    },
    'address': {},
    'center_point': {
      'lon': 0,
      'lat': 0
    },
    'category': [],
    'population': 6814400000,
    'suggest': {
      'input': [
        'earth'
      ],
      'output': 'geoname:6295630',
      'weight': 23
    }
  }];

  test('earth', function(t) {
    var json = geojsonify.search( earth, { details: true } );
    t.deepEqual(json, { bbox: undefined, features: [], type: 'FeatureCollection' }, 'foo');
    t.end();
  });

};
```

**Comment by missinglink** [comment]
This should now be resolved on live. cc/ @heffergm
