### ISSUE TITLE
Exculuding Address Layer Problem

### ISSUE THREAD

**Issue by akifaktas** [pelias/pelias#972]
`"warnings":["performance optimization: excluding 'address' layer"]`

Why does this error occur? For a local country, for example, Italy, Brazil, etc., I don't encounter such a problem, but when I set up the planet, I get this warning. While this warning appears, I usually don't get the responses I want, and it often returns an empty response.

**Comment by missinglink** [comment]
The address layer contains the vast majority of records in the index, so if the parser fails to detect both a house number and street name in the input then we exclude the address layer, this has a significant positive effect on query performance.

**Comment by akifaktas** [comment]
I might not have expressed myself clearly. Let me explain it better.

I have two different servers. I set up the planet on server A. On server B, I only set up for Turkey.

Request: `SERVER-A-PLANET/v1/autocomplete?text=West%20Gate%20Residence`
Request: `SERVER-B-TURKEY/v1/autocomplete?text=West%20Gate%20Residence`

Response SERVER-A-PLANET
```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://URL:4000/attribution",
    "query": {
      "text": "west gate residence",
      "parser": "pelias",
      "parsed_text": {
        "subject": "west gate residence",
        "venue": "west gate residence"
      },
      "size": 10,
      "layers": [
        "locality",
        "postalcode",
        "neighbourhood",
        "localadmin",
        "county",
        "region",
        "macrohood",
        "macrocounty",
        "borough",
        "marinearea",
        "country",
        "disputed",
        "macroregion",
        "dependency",
        "empire",
        "continent",
        "ocean"
      ],
      "private": false,
      "lang": {
        "name": "Turkish",
        "iso6391": "tr",
        "iso6393": "tur",
        "via": "header",
        "defaulted": false
      },
      "querySize": 20
    },
    "warnings": [
      "performance optimization: excluding 'address' layer"
    ],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1728137672761
  },
  "type": "FeatureCollection",
  "features": [
    
  ]
}
```

RESPONSE SERVER-B-TURKEY:
```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://URL:4000/attribution",
    "query": {
      "text": "West Gate Residence",
      "parser": "pelias",
      "parsed_text": {
        "subject": "West Gate Residence",
        "venue": "West Gate Residence"
      },
      "size": 10,
      "layers": [
        "venue",
        "street",
        "locality",
        "neighbourhood",
        "county",
        "region",
        "localadmin",
        "country"
      ],
      "private": false,
      "focus.point.lat": 39.93,
      "focus.point.lon": 32.87,
      "lang": {
        "name": "Turkish",
        "iso6391": "tr",
        "iso6393": "tur",
        "via": "header",
        "defaulted": false
      },
      "querySize": 20
    },
    "warnings": [
      "performance optimization: excluding 'address' layer"
    ],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1728137657119
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [32.65782, 39.878562]
      },
      "properties": {
        "id": "way/1124656685",
        "gid": "openstreetmap:venue:way/1124656685",
        "layer": "venue",
        "source": "openstreetmap",
        "source_id": "way/1124656685",
        "country_code": "TR",
        "name": "West Gate Residence",
        "distance": 19.002,
        "accuracy": "point",
        "country": "Türkiye",
        "country_gid": "whosonfirst:country:85632393",
        "country_a": "TUR",
        "region": "Ankara",
        "region_gid": "whosonfirst:region:85679409",
        "region_a": "AN",
        "county": "Çankaya",
        "county_gid": "whosonfirst:county:890462517",
        "county_a": "MA",
        "locality": "Ankara",
        "locality_gid": "whosonfirst:locality:890460453",
        "label": "West Gate Residence, Ankara, Türkiye"
      },
      "bbox": [32.6565548, 39.8781731, 32.6590086, 39.878888]
    }
  ],
  "bbox": [32.6565548, 39.8781731, 32.6590086, 39.878888]
}
```

The setups are exactly the same; I did them using Docker. However, while the relevant object cannot be found on the planet setup, the locally scoped one is able to respond. What could be the exact issue? By the way thanks @missinglink

**Comment by missinglink** [comment]
It seems that the PBF file you used to import the planet doesn't contain that way.

Which data did you use?

Try running `pelias elastic stats` against each to get a summary of what's in the index, maybe the openstreetmap importer failed completely?

**Comment by akifaktas** [comment]
pelias elastic stats
```
{
  "took" : 93,
  "timed_out" : false,
  "_shards" : {
    "total" : 12,
    "successful" : 12,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "sources" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "openaddresses",
          "doc_count" : 80066497,
          "layers" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [
              {
                "key" : "address",
                "doc_count" : 80066497
              }
            ]
          }
        },
        {
          "key" : "whosonfirst",
          "doc_count" : 8287773,
          "layers" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [
              {
                "key" : "locality",
                "doc_count" : 4744842
              },
              {
                "key" : "postalcode",
                "doc_count" : 3063012
              },
              {
                "key" : "neighbourhood",
                "doc_count" : 292751
              },
              {
                "key" : "localadmin",
                "doc_count" : 138256
              },
              {
                "key" : "county",
                "doc_count" : 41534
              },
              {
                "key" : "region",
                "doc_count" : 4244
              },
              {
                "key" : "macrohood",
                "doc_count" : 1228
              },
              {
                "key" : "macrocounty",
                "doc_count" : 575
              },
              {
                "key" : "borough",
                "doc_count" : 450
              },
              {
                "key" : "marinearea",
                "doc_count" : 402
              },
              {
                "key" : "country",
                "doc_count" : 213
              },
              {
                "key" : "disputed",
                "doc_count" : 100
              },
              {
                "key" : "macroregion",
                "doc_count" : 100
              },
              {
                "key" : "dependency",
                "doc_count" : 40
              },
              {
                "key" : "empire",
                "doc_count" : 11
              },
              {
                "key" : "continent",
                "doc_count" : 8
              },
              {
                "key" : "ocean",
                "doc_count" : 7
              }
            ]
          }
        }
      ]
    }
  }
```

It seems that there is data, but could you take a look as well? Is it possible that there is missing data?

**Comment by missinglink** [comment]
Your index contains no openstreetmap data.

**Comment by akifaktas** [comment]
I previously encountered an error like this. Could it be related?

```
/data/openstreetmap/planet-latest.osm.pbf is very large.
We strongly recommend using Valhalla to produce extracts for large PBF extracts.
You can also download pre-processed polyline extracts from Geocode Earth.
see: https://github.com/pelias/polylines#download-data
```

**Comment by missinglink** [comment]
> I previously encountered an error like this. Could it be related?

This is also a problem, although I related. It would have appeared when running the `pelias prepare polylines` command, it's regarding the memory requirements for processing all the streets in the world and will result in not having any records ok the street `layer`.

The issue you seem to be affected by is not that there are no records on the `address` layer (as per the Issue title), you can see that you have 80 million in your index, it's that the openstreetmap importer failed.

Did you run `pelias import osm`?
Try running that command again.

**Comment by akifaktas** [comment]
Run; `pelias import osm`

Response:
```
info: [openstreetmap] Creating read stream for: /mnt/pelias/openstreetmap/planet-latest.osm.pbf
/code/pelias/openstreetmap/stream/pbf.js:63
    throw new Error( message );
    ^

Error: failed to stat pbf file: /mnt/pelias/openstreetmap/planet-latest.osm.pbf
    at validatePath (/code/pelias/openstreetmap/stream/pbf.js:63:11)
    at Object.createPbfStream [as parser] (/code/pelias/openstreetmap/stream/pbf.js:18:3)
    at /code/pelias/openstreetmap/stream/multiple_pbfs.js:18:16
    at CombinedStream._realGetNext (/code/pelias/openstreetmap/node_modules/combined-stream/lib/combined_stream.js:104:3)
    at CombinedStream._getNext (/code/pelias/openstreetmap/node_modules/combined-stream/lib/combined_stream.js:82:12)
    at CombinedStream.resume (/code/pelias/openstreetmap/node_modules/combined-stream/lib/combined_stream.js:154:10)
    at CombinedStream.pipe (/code/pelias/openstreetmap/node_modules/combined-stream/lib/combined_stream.js:66:8)
    at Object.streams.import (/code/pelias/openstreetmap/stream/importPipeline.js:25:6)
    at Object.<anonymous> (/code/pelias/openstreetmap/index.js:12:22)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```


However, my pelias.json is as follows:

```
 "openstreetmap": {
      "download": [
        { "sourceURL": "https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf" }
      ],
      "datapath": "/data/openstreetmap",
      "import": [{
        "filename": "planet-latest.osm.pbf"
      }]
    },
```

Indeed, when I checked, the file is located at /data/openstreetmap/planet-latest.osm.pbf.

Why is it looking for the file at this location => `/mnt/pelias/openstreetmap/planet-latest.osm.pbf`

 and how can I adjust it?

**Comment by missinglink** [comment]
You seem to have configured the source as `planet-latest.osm.pbf` but the file is named `planet-daily.osm.pbf` on disk?

You can adjust it I the `pelias.json` file, the name in the config section you posted must match the name of the file on disk.
